#Placeholder messages:
# %gens_limit% - The players current gen limit
# %gens_placed% - The players amount of gens placed
# %gens_event% - The current event
# ~Placeholders
#Event messages: (supports chat colors)
Upgrade-Event-Message: "&7[&aGens&7] &aNew event: Upgrade event."
Double-Event-Message: "&7[&aGens&7] &aNew event: Double drop event."
Sell-Event-Message: "&7[&aGens&7] &aNew event: Sell event."
Inactive-Event-Message: "&7[&aGens&7] &cEvent: Inactive."
#Mode-Selection-Interval :: The time in minutes, where the event will be inactive.
Mode-Selection-Interval: 1
#Event-Interval :: The time in minutes, for the event to be active.
Event-Interval: 1
Generators:
  wheat:
    tier: 1
    delay: 7
    price: 100
    material: HAY_BLOCK
    display:
     name: "&eWheat Generator"
     lore:
      - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
      - ""
      - "&7Tier 1 generator."
      - "&7Price: &a$&f%price%"
      - ""
      - "&7Delay: &f%delay%s"
  coal:
    tier: 2
    delay: 7
    price: 500
    material: COAL_BLOCK
    display:
     name: "&8Coal Generator"
     lore:
       - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
       -
       - "&7Tier 2 generator."
       - "&7Price: &a$&f%price%"
       - ""
       - "&7Delay: &f%delay%s"
  iron:
    tier: 3
    delay: 6
    price: 1000
    material: IRON_BLOCK
    display:
      name: "&7Iron Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 3 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  gold:
    tier: 4
    delay: 5
    price: 2000
    material: GOLD_BLOCK
    display:
      name: "&2Gold Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 4 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  diamond:
    tier: 5
    delay: 5
    price: 4000
    material: DIAMOND_BlOCK
    display:
      name: "&bDiamond Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&bTier 5 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  emerald:
    tier: 6
    delay: 3
    price: 8000
    material: EMERALD_BLOCK
    display:
      name: "&aEmerald Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&aTier 6 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
# Below is a list of all generator drops. Please ensure that the drop matches the correct generator tier!
Drops:
  wheat:
    tier: 1
    price: 50
    material: WHEAT
    display:
      name: "&eWheat"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&eObtained from Tier 1 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  coal:
    tier: 2
    price: 100
    material: COAL
    display:
      name: "&eCoal"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 2 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  iron:
    tier: 3
    price: 200
    material: IRON_INGOT
    display:
      name: "&eIron"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 3 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  gold:
    tier: 4
    price: 300
    material: GOLD_INGOT
    display:
      name: "&eGold"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 4 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  diamond:
    tier: 5
    price: 400
    material: DIAMOND
    display:
      name: "&bDiamond"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        -
        - "&bObtained from Tier 5 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  emerald:
    tier: 6
    price: 500
    material: EMERALD
    display:
      name: "&aEmerald"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&aObtained from Tier 6 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"