Generators:
  wheat:
    tier: 1
    price: 100
    material: HAY_BLOCK
    display:
     name: "&eWheat Generator"
     lore:
      - "&eWheat Generator"
      - "&7Tier 1 generator."
      - ""
      - "&eClick to buy!"
  coal:
    tier: 2
    price: 500
    material: COAL_BLOCK
    display:
     name: "&8Coal Generator"
     lore:
       - "&7Coal Generator"
       - "&7Tier 2 generator."
       - ""
       - "&eClick to buy!"
  iron:
    tier: 3
    price: 1000
    material: IRON_BLOCK
    display:
      name: "&7Iron Generator"
      lore:
        - "&7Iron Generator"
        - "&7Tier 3 generator."
        - ""
        - "&eClick to buy!"
  gold:
    tier: 4
    price: 2000
    material: GOLD_BLOCK
    display:
      name: "&2Gold Generator"
      lore:
        - "&7Gold Generator"
        - "&7Tier 4 generator."
        - ""
        - "&eClick to buy!"
  diamond:
    tier: 5
    price: 4000
    material: DIAMOND_BlOCK
    display:
      name: "&bDiamond Generator"
      lore:
        - "&bDiamond Generator"
        - "&bTier 5 generator."
        - ""
        - "&eClick to buy!"
  emerald:
    tier: 6
    price: 8000
    material: EMERALD_BLOCK
    display:
      name: "&aEmerald Generator"
      lore:
        - "&aEmerald Generator"
        - "&aTier 6 generator."
        - ""
        - "&eClick to buy!"
# Below is a list of all generator drops. Please ensure that the drop matches the correct generator tier!
Drops:
  wheat:
    tier: 1
    price: 50
    material: WHEAT
    display:
      name: "&eWheat"
      lore:
        - "&eGenerator wheat"
        - "&eObtained from Tier 1 Generator"
        - "Sell via &a/sell&r command!"
  coal:
    tier: 2
    price: 100
    material: COAL
    display:
      name: "&eCoal"
      lore:
        - "&7Coal"
        - "&7Obtained from Tier 2 Generator"
        - "Sell via &a/sell&r command!"
  iron:
    tier: 3
    price: 200
    material: IRON_INGOT
    display:
      name: "&eIron"
      lore:
        - "&7Iron Ingot"
        - "&7Obtained from Tier 3 Generator"
        - "Sell via &a/sell&r command!"
  gold:
    tier: 4
    price: 300
    material: GOLD_INGOT
    display:
      name: "&eGold"
      lore:
        - "&7Gold Ingot"
        - "&7Obtained from Tier 4 Generator"
        - "Sell via &a/sell&r command!"
  diamond:
    tier: 5
    price: 400
    material: DIAMOND
    display:
      name: "&bDiamond"
      lore:
        - "&bDiamond Ore"
        - "&bObtained from Tier 5 Generator"
        - "Sell via &a/sell&r command!"
  emerald:
    tier: 6
    price: 500
    material: EMERALD
    display:
      name: "&aEmerald"
      lore:
        - "&aEmerald Ore"
        - "&aObtained from Tier 6 Generator"
        - "Sell via &a/sell&r command!"