#Placeholder messages:
# %gens_limit% - The players current gen limit
# %gens_placed% - The players amount of gens placed
# %gens_event% - The current event
# ~Placeholders
#Event messages: (supports chat colors)
Upgrade-Event-Message: "&7[&aGens&7] &aNew event: Upgrade event."
Double-Event-Message: "&7[&aGens&7] &aNew event: Double drop event."
Sell-Event-Message: "&7[&aGens&7] &aNew event: Sell event."
Inactive-Event-Message: "&7[&aGens&7] &cEvent: Inactive."
#Mode-Selection-Interval :: The time in minutes, where the event will be inactive.
Mode-Selection-Interval: 1
#Event-Interval :: The time in minutes, for the event to be active.
Event-Interval: 1
Generators:
  wheat:
    tier: 1
    delay: 7
    price: 1000
    material: HAY_BLOCK
    display:
      name: "&e&lWheat Generator (Tier 1)"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 1 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  melon:
    tier: 2
    delay: 7
    price: 2500
    material: MELON
    display:
      name: "&e&lMelon Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 2 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  coalore:
    tier: 3
    delay: 7
    price: 3500
    material: COAL_ORE
    display:
      name: "&8&lCoal Ore Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        -
        - "&7Tier 3 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  coalblock:
    tier: 4
    delay: 7
    price: 5000
    material: COAL_BLOCK
    display:
      name: "&8&lCoal Block Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        -
        - "&7Tier 4 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  ironore:
    tier: 5
    delay: 6
    price: 7500
    material: IRON_ORE
    display:
      name: "&7&lIron Ore Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 5 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  ironblock:
    tier: 6
    delay: 6
    price: 10000
    material: IRON_BLOCK
    display:
      name: "&7&lIron Block Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 6 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  goldore:
    tier: 7
    delay: 5
    price: 15000
    material: GOLD_ORE
    display:
      name: "&2&lGold Ore Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 7 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  goldblock:
    tier: 8
    delay: 5
    price: 20000
    material: GOLD_BLOCK
    display:
      name: "&2&lGold Block Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&7Tier 8 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  diamondore:
    tier: 9
    delay: 5
    price: 30000
    material: DIAMOND_ORE
    display:
      name: "&b&lDiamond Ore Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&bTier 9 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  diamondblock:
    tier: 10
    delay: 5
    price: 40000
    material: DIAMOND_BlOCK
    display:
      name: "&b&lDiamond Block Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&bTier 10 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  emeraldore:
    tier: 11
    delay: 3
    price: 60000
    material: EMERALD_ORE
    display:
      name: "&a&lEmerald Ore Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&aTier 11 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  emeraldblock:
    tier: 12
    delay: 3
    price: 80000
    material: EMERALD_BLOCK
    display:
      name: "&a&lEmerald Block Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&aTier 12 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
  netherrack:
    tier: 13
    delay: 3
    price: 100000
    material: NETHERRACK
    display:
      name: "&c&lNetherrack Generator"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ"
        - ""
        - "&aTier 13 generator."
        - "&7Price: &a$&f%price%"
        - ""
        - "&7Delay: &f%delay%s"
# Below is a list of all generator drops. Please ensure that the drop matches the correct generator tier!
Drops:
  wheat:
    tier: 1
    price: 1
    material: WHEAT
    display:
      name: "&eWheat"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&eObtained from Tier 1 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  melon:
    tier: 2
    price: 2
    material: MELON_SLICE
    display:
      name: "&e&lMelon"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&eObtained from Tier 2 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  coalore:
    tier: 3
    price: 5
    material: COAL
    display:
      name: "&eCoal"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 3 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  coalblock:
    tier: 4
    price: 7.5
    material: COAL_BLOCK
    display:
      name: "&e&lCoal Block"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 4 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  ironore:
    tier: 5
    price: 10
    material: IRON_INGOT
    display:
      name: "&e&lIron"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 3 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  ironblock:
    tier: 6
    price: 12.5
    material: IRON_BLOCK
    display:
      name: "&e&lIron"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 6 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  goldore:
    tier: 7
    price: 17.5
    material: GOLD_INGOT
    display:
      name: "&e&lGold ingot"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 7 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  goldblock:
    tier: 8
    price: 20
    material: GOLD_BLOCK
    display:
      name: "&e&lGold Block"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&7Obtained from Tier 8 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  diamondore:
    tier: 9
    price: 22.5
    material: DIAMOND
    display:
      name: "&b&lDiamond"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        -
        - "&bObtained from Tier 9 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  diamondblock:
    tier: 10
    price: 25
    material: DIAMOND_BLOCK
    display:
      name: "&b&lDiamond Block"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        -
        - "&bObtained from Tier 10 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  emerald:
    tier: 11
    price: 27.5
    material: EMERALD
    display:
      name: "&a&lEmerald"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&aObtained from Tier 11 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  emeraldblock:
    tier: 12
    price: 30
    material: EMERALD_BLOCK
    display:
      name: "&a&lEmerald Block"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&aObtained from Tier 12 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"
  netherrack:
    tier: 13
    price: 35
    material: NETHERRACK
    display:
      name: "&c&lNetherrack"
      lore:
        - "&8ɢᴇɴᴇʀᴀᴛᴏʀ ᴅʀᴏᴘ"
        - ""
        - "&aObtained from Tier 13 Generator"
        - "&7Sell via &a/sell&r command!"
        - "&7Value: &a$%price%"